parameters:

services:
  _defaults:
    autowire: true
    public: false
    autoconfigure: true

  DTOServiceBundle\:
    resource: '../'
    exclude:
      - '../DependencyInjection/'
      - '../DTOServiceBundle.php'

  pgb.dto_service:
    class: DTOServiceBundle\DTOService
  DTOServiceBundle\DTOService: '@pgb.dto_service'